version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8 
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install pytest pandas matplotlib openpyxl
      - run:
          name: Run tests
          command: pytest Test_Suite.py

workflows:
  version: 2
  build:
    jobs:
      - build
